trigger:
  - master

pool:
  name: Default

steps:
  - script: echo "My first Azure Pipeline for Maven project"
    displayName: 'Run a one-line script'

  - script: mvn clean install
    displayName: 'Build with Maven'

  - script: ls -la target
    displayName: 'List target directory contents'

  - script: java -jar target/MyMavenGuavaApp-1.0-SNAPSHOT.jar
    displayName: 'Run the JAR file'
